### PR TITLE
Application for memebership

### PR DESCRIPTION
**Pull request by martindanielsson**
Like this?

### CODE REVIEW

**Comment by jongotlin** [comment]
Add Github username maybe?

**Comment by Nyholm** [comment]
👍

**Comment by martindanielsson** [comment]
Or do you want to split the optionals down a level?

```
"optionals": {
  . . .
}
```

**Comment by Nyholm** [comment]
I do not think so. Lets put everything on one level.

**Comment by Nyholm** [comment]
Awesome! Our first real member!

**Pull request merged**
