### PR TITLE
Adding Tobias

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for merging. Did you like the linter?

**Comment by nicholasruunu** [comment]
I would've probably gone with a npm solution, but whatever works. :)
Perhaps add it as a script to composer.json at least.

**Comment by Nyholm** [comment]
> I would've probably gone with a npm solution,

You kids...  =)

> Perhaps add it as a script to composer.json at least.

Sure, please do

**Comment by nicholasruunu** [comment]
Done. (:

**Pull request merged**
